// Bu dosya tools/build_data.py ile üretilir. Elle düzenlemeyin.
window.PEDDOSE_DATA = {
 "ilaclar": [
  {
   "id": "ondansetron_iv",
   "ilac_adi": "Zofran",
   "etken_madde": "Ondansetron",
   "markalar": "Zofran",
   "yol": "IV",
   "kategoriler": [
    "Antiemetik"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.15,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 8.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "8 saatte bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 2.0,
   "birim_adi": "ampul",
   "birim_miktar": 4.0,
   "birim_ml": 2.0,
   "form_adi": "4 mg/2 mL ampul",
   "not": ""
  },
  {
   "id": "parasetamol_iv",
   "ilac_adi": "Parol IV",
   "etken_madde": "Parasetamol",
   "markalar": "Parol",
   "yol": "IV",
   "kategoriler": [
    "Ateş",
    "Ağrı"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 15.0,
   "doz_10kg_alti_per_kg": 7.5,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1000.0,
   "gunluk_max_per_kg": 60.0,
   "gunluk_max": 4000.0,
   "tekrar_araligi": "6 saatte bir (dozlar arası en az 4 saat)",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 10.0,
   "birim_adi": "flakon",
   "birim_miktar": 1000.0,
   "birim_ml": 100.0,
   "form_adi": "1000 mg/100 mL flakon",
   "not": "15 dakikada infüzyon. 10 kg altında günlük max 30 mg/kg."
  },
  {
   "id": "feniramin_iv",
   "ilac_adi": "Avil",
   "etken_madde": "Feniramin maleat",
   "markalar": "Avil",
   "yol": "IV/IM",
   "kategoriler": [
    "Alerji/Anafilaksi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 1.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 45.5,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "12 saatte bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 22.75,
   "birim_adi": "ampul",
   "birim_miktar": 45.5,
   "birim_ml": 2.0,
   "form_adi": "45.5 mg/2 mL ampul",
   "not": ""
  },
  {
   "id": "ibuprofen_iv",
   "ilac_adi": "Brufen IV",
   "etken_madde": "İbuprofen",
   "markalar": "Brufen; Dorifen",
   "yol": "IV",
   "kategoriler": [
    "Ateş",
    "Ağrı",
    "NSAİİ"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 10.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 400.0,
   "gunluk_max_per_kg": 40.0,
   "gunluk_max": 2400.0,
   "tekrar_araligi": "6-8 saatte bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 4.0,
   "birim_adi": "şişe",
   "birim_miktar": 400.0,
   "birim_ml": 100.0,
   "form_adi": "400 mg/100 mL şişe",
   "not": "En az 10 dakikada infüzyon. 6 aydan küçükte kullanılmaz."
  },
  {
   "id": "parasetamol_po_120",
   "ilac_adi": "Calpol",
   "etken_madde": "Parasetamol",
   "markalar": "Calpol",
   "yol": "PO",
   "kategoriler": [
    "Ateş",
    "Ağrı"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 15.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1000.0,
   "gunluk_max_per_kg": 60.0,
   "gunluk_max": 4000.0,
   "tekrar_araligi": "6 saatte bir (dozlar arası en az 4 saat)",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 24.0,
   "birim_adi": "ölçek",
   "birim_miktar": 120.0,
   "birim_ml": 5.0,
   "form_adi": "120 mg/5 mL şurup",
   "not": ""
  },
  {
   "id": "parasetamol_po_250",
   "ilac_adi": "Calpol 6 Plus",
   "etken_madde": "Parasetamol",
   "markalar": "Calpol 6 Plus",
   "yol": "PO",
   "kategoriler": [
    "Ateş",
    "Ağrı"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 15.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1000.0,
   "gunluk_max_per_kg": 60.0,
   "gunluk_max": 4000.0,
   "tekrar_araligi": "6 saatte bir (dozlar arası en az 4 saat)",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "ölçek",
   "birim_miktar": 250.0,
   "birim_ml": 5.0,
   "form_adi": "250 mg/5 mL şurup",
   "not": "6 yaş ve üstü için."
  },
  {
   "id": "ibuprofen_po",
   "ilac_adi": "Brufen şurup",
   "etken_madde": "İbuprofen",
   "markalar": "Brufen; Dorifen",
   "yol": "PO",
   "kategoriler": [
    "Ateş",
    "Ağrı",
    "NSAİİ"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 10.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 400.0,
   "gunluk_max_per_kg": 40.0,
   "gunluk_max": 2400.0,
   "tekrar_araligi": "6-8 saatte bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 20.0,
   "birim_adi": "ölçek",
   "birim_miktar": 100.0,
   "birim_ml": 5.0,
   "form_adi": "100 mg/5 mL şurup",
   "not": "6 aydan küçükte kullanılmaz."
  },
  {
   "id": "epinefrin_iv_arrest",
   "ilac_adi": "Adrenalin IV/IO (arrest)",
   "etken_madde": "Epinefrin",
   "markalar": "Adrenalin",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.01,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "3-5 dakikada bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.1,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul (1:1000)",
   "not": "1 mg ampul SF ile 10 mL'ye sulandırılır (0,1 mg/mL = 1:10.000). mL bu sulandırmaya göredir."
  },
  {
   "id": "epinefrin_et",
   "ilac_adi": "Adrenalin ET",
   "etken_madde": "Epinefrin",
   "markalar": "Adrenalin",
   "yol": "ET",
   "kategoriler": [
    "Resüsitasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2.5,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "3-5 dakikada bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul (1:1000)",
   "not": "Sulandırılmadan (1 mg/mL) verilir. IV/IO yol yoksa kullanılır."
  },
  {
   "id": "epinefrin_im",
   "ilac_adi": "Adrenalin IM (anafilaksi)",
   "etken_madde": "Epinefrin",
   "markalar": "Adrenalin",
   "yol": "IM",
   "kategoriler": [
    "Resüsitasyon",
    "Alerji/Anafilaksi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.01,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 0.5,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "5-15 dakikada bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul (1:1000)",
   "not": "Sulandırılmadan, uyluk dış yanına verilir."
  },
  {
   "id": "epinefrin_neb",
   "ilac_adi": "Adrenalin nebül",
   "etken_madde": "Epinefrin",
   "markalar": "Adrenalin",
   "yol": "Nebül",
   "kategoriler": [
    "Resüsitasyon",
    "Solunum",
    "Krup"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 5.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul (1:1000)",
   "not": "Krup: 0,5 mL/kg (max 5 mL), 1 mg/mL koruyucusuz adrenalin. 5-15 dakikada nebülize edilir. Toplam hacim 3 mL'den azsa SF ile 3 mL'ye tamamlanır."
  },
  {
   "id": "atropin_iv_bradikardi",
   "ilac_adi": "Atropin IV/IO (bradikardi)",
   "etken_madde": "Atropin sülfat",
   "markalar": "Atropin",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Aritmi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.02,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": 0.1,
   "tek_doz_max": 0.5,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "1 kez tekrarlanabilir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul",
   "not": ""
  },
  {
   "id": "atropin_opp",
   "ilac_adi": "Atropin IV/IM (OPP)",
   "etken_madde": "Atropin sülfat",
   "markalar": "Atropin",
   "yol": "IV/IM",
   "kategoriler": [
    "Resüsitasyon",
    "Zehirlenme"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.02,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": 0.1,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "5 dakikada bir, doz iki katına çıkarılarak",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul",
   "not": "Organofosfat zehirlenmesi. Atropinizasyon (sekresyonlar kuruyana kadar) sağlanana kadar sürdürülür."
  },
  {
   "id": "atropin_et",
   "ilac_adi": "Atropin ET",
   "etken_madde": "Atropin sülfat",
   "markalar": "Atropin",
   "yol": "ET",
   "kategoriler": [
    "Resüsitasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.04,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul",
   "not": ""
  },
  {
   "id": "adenozin_1",
   "ilac_adi": "Adenozin 1. doz",
   "etken_madde": "Adenozin",
   "markalar": "Adenocor",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Aritmi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 6.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 3.0,
   "birim_adi": "ampul",
   "birim_miktar": 6.0,
   "birim_ml": 2.0,
   "form_adi": "6 mg/2 mL ampul",
   "not": "Hızlı IV puşe, hemen ardından 5-10 mL SF ile hızlı yıkama."
  },
  {
   "id": "adenozin_2",
   "ilac_adi": "Adenozin 2. doz",
   "etken_madde": "Adenozin",
   "markalar": "Adenocor",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Aritmi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.2,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 12.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 3.0,
   "birim_adi": "ampul",
   "birim_miktar": 6.0,
   "birim_ml": 2.0,
   "form_adi": "6 mg/2 mL ampul",
   "not": "1. doz yanıtsızsa. Hızlı IV puşe, hemen ardından 5-10 mL SF ile hızlı yıkama."
  },
  {
   "id": "midazolam_iv",
   "ilac_adi": "Midazolam IV",
   "etken_madde": "Midazolam",
   "markalar": "Dormicum",
   "yol": "IV",
   "kategoriler": [
    "Resüsitasyon",
    "Nöbet",
    "Sedasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 5.0,
   "birim_adi": "ampul",
   "birim_miktar": 15.0,
   "birim_ml": 3.0,
   "form_adi": "15 mg/3 mL ampul",
   "not": "5 mg/5 mL (1 mg/mL) ampul kullanılırsa mL farklıdır."
  },
  {
   "id": "midazolam_in_im",
   "ilac_adi": "Midazolam IN/IM",
   "etken_madde": "Midazolam",
   "markalar": "Dormicum",
   "yol": "IN/IM",
   "kategoriler": [
    "Resüsitasyon",
    "Nöbet"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.2,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 10.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 5.0,
   "birim_adi": "ampul",
   "birim_miktar": 15.0,
   "birim_ml": 3.0,
   "form_adi": "15 mg/3 mL ampul",
   "not": "IN: dozu iki burun deliğine bölün."
  },
  {
   "id": "morfin_iv_im",
   "ilac_adi": "Morfin IV/IM",
   "etken_madde": "Morfin sülfat",
   "markalar": "Morfin",
   "yol": "IV/IM",
   "kategoriler": [
    "Resüsitasyon",
    "Ağrı"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2-4 saatte bir",
   "kilo_min_kg": 8.0,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 10.0,
   "birim_adi": "ampul",
   "birim_miktar": 10.0,
   "birim_ml": 1.0,
   "form_adi": "10 mg/1 mL ampul",
   "not": "Broselow tablosunda 8 kg altı için verilmemiş."
  },
  {
   "id": "glukagon_im_25alti",
   "ilac_adi": "Glukagon IM",
   "etken_madde": "Glukagon",
   "markalar": "GlucaGen",
   "yol": "IM",
   "kategoriler": [
    "Resüsitasyon",
    "Hipoglisemi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": null,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": 0.5,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": 25.0,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "flakon",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL kit",
   "not": "25 kg altı sabit doz."
  },
  {
   "id": "glukagon_im_25ustu",
   "ilac_adi": "Glukagon IM",
   "etken_madde": "Glukagon",
   "markalar": "GlucaGen",
   "yol": "IM",
   "kategoriler": [
    "Resüsitasyon",
    "Hipoglisemi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": null,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": 1.0,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": 25.0,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "flakon",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL kit",
   "not": "25 kg ve üstü sabit doz."
  },
  {
   "id": "bikarbonat_iv",
   "ilac_adi": "Sodyum bikarbonat %8,4",
   "etken_madde": "Sodyum bikarbonat",
   "markalar": "",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon"
   ],
   "doz_birimi": "mEq",
   "doz_per_kg": 1.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 50.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 10.0,
   "birim_ml": 10.0,
   "form_adi": "10 mEq/10 mL ampul (%8,4)",
   "not": "Yenidoğan ve küçük bebekte 1:1 sulandırılır (%4,2)."
  },
  {
   "id": "dekstroz_10",
   "ilac_adi": "Dekstroz %10",
   "etken_madde": "Dekstroz",
   "markalar": "",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Hipoglisemi"
   ],
   "doz_birimi": "g",
   "doz_per_kg": 0.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 25.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.1,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "%10 dekstroz (0,1 g/mL)",
   "not": "0,5 g/kg = 5 mL/kg."
  },
  {
   "id": "nalokson",
   "ilac_adi": "Nalokson",
   "etken_madde": "Nalokson",
   "markalar": "Narcan",
   "yol": "IV/IM/IN",
   "kategoriler": [
    "Resüsitasyon",
    "Zehirlenme"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2-3 dakikada bir, gerekirse",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.4,
   "birim_adi": "ampul",
   "birim_miktar": 0.4,
   "birim_ml": 1.0,
   "form_adi": "0.4 mg/1 mL ampul",
   "not": ""
  },
  {
   "id": "sf_bolus",
   "ilac_adi": "SF bolus",
   "etken_madde": "%0,9 NaCl",
   "markalar": "",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Sıvı"
   ],
   "doz_birimi": "mL",
   "doz_per_kg": 20.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": null,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "%0,9 NaCl",
   "not": "Gerekirse tekrarlanır; her bolustan sonra yeniden değerlendirilir."
  },
  {
   "id": "deksametazon_krup",
   "ilac_adi": "Deksametazon (krup)",
   "etken_madde": "Deksametazon",
   "markalar": "Dekort",
   "yol": "PO/IV/IM",
   "kategoriler": [
    "Krup"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.6,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 16.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 4.0,
   "birim_adi": "ampul",
   "birim_miktar": 8.0,
   "birim_ml": 2.0,
   "form_adi": "8 mg/2 mL ampul",
   "not": "En az invaziv yol: ağızdan alabiliyorsa PO, damar yolu varsa IV, ikisi de yoksa IM. PO için ampul ağızdan verilebilir (şurupla karıştırılabilir) veya tablet ezilip püre ile verilir."
  }
 ],
 "broselow": [
  {
   "renk": "Gri / Pembe",
   "kilo_min_kg": 0.0,
   "kilo_max_kg": 8.0,
   "kilo_araligi": "<8 kg",
   "ornek_kilo": "~5 kg",
   "boy_cm": "46–59",
   "et_tup_kafsiz_mm": "3.5",
   "et_tup_kafli_mm": "3.0",
   "ng_tup": "5 Fr",
   "defib_1_sok": "10 J",
   "defib_2_3_sok": "20 J",
   "kardiyoversiyon_1_sok": "5 J",
   "kardiyoversiyon_2_3_sok": "10 J"
  },
  {
   "renk": "Kırmızı / Mor / Sarı",
   "kilo_min_kg": 8.0,
   "kilo_max_kg": 15.0,
   "kilo_araligi": "8–14 kg",
   "ornek_kilo": "~10 kg",
   "boy_cm": "67–95",
   "et_tup_kafsiz_mm": "3.5 (K) / 4.0 (M) / 4.5 (S)",
   "et_tup_kafli_mm": "3.0 (K) / 3.5 (M) / 4.0 (S)",
   "ng_tup": "5–8 (K) / 8–10 (M) / 10 (S) Fr",
   "defib_1_sok": "20 J",
   "defib_2_3_sok": "40 J",
   "kardiyoversiyon_1_sok": "10 J",
   "kardiyoversiyon_2_3_sok": "20 J"
  },
  {
   "renk": "Beyaz",
   "kilo_min_kg": 15.0,
   "kilo_max_kg": 19.0,
   "kilo_araligi": "15–18 kg",
   "ornek_kilo": "~15 kg",
   "boy_cm": "96–107",
   "et_tup_kafsiz_mm": "5",
   "et_tup_kafli_mm": "4.5",
   "ng_tup": "10 Fr",
   "defib_1_sok": "30 J",
   "defib_2_3_sok": "60 J",
   "kardiyoversiyon_1_sok": "15 J",
   "kardiyoversiyon_2_3_sok": "30 J"
  },
  {
   "renk": "Mavi",
   "kilo_min_kg": 19.0,
   "kilo_max_kg": 24.0,
   "kilo_araligi": "19–23 kg",
   "ornek_kilo": "~20 kg",
   "boy_cm": "108–117",
   "et_tup_kafsiz_mm": "5.5",
   "et_tup_kafli_mm": "5.0",
   "ng_tup": "12–14 Fr",
   "defib_1_sok": "40 J",
   "defib_2_3_sok": "80 J",
   "kardiyoversiyon_1_sok": "20 J",
   "kardiyoversiyon_2_3_sok": "40 J"
  },
  {
   "renk": "Turuncu",
   "kilo_min_kg": 24.0,
   "kilo_max_kg": 30.0,
   "kilo_araligi": "24–29 kg",
   "ornek_kilo": "~25 kg",
   "boy_cm": "118–127",
   "et_tup_kafsiz_mm": "6",
   "et_tup_kafli_mm": "5.5",
   "ng_tup": "14–18 Fr",
   "defib_1_sok": "50 J",
   "defib_2_3_sok": "100 J",
   "kardiyoversiyon_1_sok": "25 J",
   "kardiyoversiyon_2_3_sok": "50 J"
  },
  {
   "renk": "Yeşil",
   "kilo_min_kg": 30.0,
   "kilo_max_kg": 37.0,
   "kilo_araligi": "30–36 kg",
   "ornek_kilo": "~35 kg",
   "boy_cm": "128–143",
   "et_tup_kafsiz_mm": "6.5",
   "et_tup_kafli_mm": "6.0",
   "ng_tup": "18 Fr",
   "defib_1_sok": "70 J",
   "defib_2_3_sok": "140 J",
   "kardiyoversiyon_1_sok": "35 J",
   "kardiyoversiyon_2_3_sok": "70 J"
  }
 ]
};
