// Bu dosya tools/build_data.py ile üretilir. Elle düzenlemeyin.
window.PEDDOSE_DATA = {
 "ilaclar": [
  {
   "id": "ondansetron_iv",
   "ilac_adi": "Ondansetron",
   "etken_madde": "Ondansetron",
   "markalar": "Zofran",
   "yol": "IV",
   "kategoriler": [
    "Sık kullanılanlar",
    "Antiemetik"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.15,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 8.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "3x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 2.0,
   "birim_adi": "ampul",
   "birim_miktar": 4.0,
   "birim_ml": 2.0,
   "form_adi": "4 mg/2 mL ampul",
   "not": "",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "parasetamol_iv",
   "ilac_adi": "Parasetamol",
   "etken_madde": "Parasetamol",
   "markalar": "Parol",
   "yol": "IV",
   "kategoriler": [
    "Sık kullanılanlar",
    "Ateş",
    "Ağrı"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 15.0,
   "doz_10kg_alti_per_kg": 7.5,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1000.0,
   "gunluk_max_per_kg": 60.0,
   "gunluk_max": 4000.0,
   "tekrar_araligi": "4x1 (dozlar arası en az 4 saat)",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 10.0,
   "birim_adi": "flakon",
   "birim_miktar": 1000.0,
   "birim_ml": 100.0,
   "form_adi": "1000 mg/100 mL flakon",
   "not": "15 dakikada infüzyon. 10 kg altında günlük max 30 mg/kg.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "feniramin_iv",
   "ilac_adi": "Feniramin",
   "etken_madde": "Feniramin maleat",
   "markalar": "Avil",
   "yol": "IV/IM",
   "kategoriler": [
    "Alerji/Anafilaksi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 1.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 45.5,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 22.75,
   "birim_adi": "ampul",
   "birim_miktar": 45.5,
   "birim_ml": 2.0,
   "form_adi": "45.5 mg/2 mL ampul",
   "not": "",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "ibuprofen_iv",
   "ilac_adi": "İbuprofen",
   "etken_madde": "İbuprofen",
   "markalar": "Brufen; Dorifen",
   "yol": "IV",
   "kategoriler": [
    "Sık kullanılanlar",
    "Ateş",
    "Ağrı",
    "NSAİİ"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 10.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 400.0,
   "gunluk_max_per_kg": 40.0,
   "gunluk_max": 2400.0,
   "tekrar_araligi": "3-4x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 4.0,
   "birim_adi": "şişe",
   "birim_miktar": 400.0,
   "birim_ml": 100.0,
   "form_adi": "400 mg/100 mL şişe",
   "not": "En az 10 dakikada infüzyon. 6 aydan küçükte kullanılmaz.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "parasetamol_po_120",
   "ilac_adi": "Parasetamol 120 mg/5 mL",
   "etken_madde": "Parasetamol",
   "markalar": "Calpol",
   "yol": "PO",
   "kategoriler": [
    "Sık kullanılanlar",
    "Şuruplar",
    "Ateş",
    "Ağrı"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 15.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1000.0,
   "gunluk_max_per_kg": 60.0,
   "gunluk_max": 4000.0,
   "tekrar_araligi": "4x1 (dozlar arası en az 4 saat)",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 24.0,
   "birim_adi": "ölçek",
   "birim_miktar": 120.0,
   "birim_ml": 5.0,
   "form_adi": "120 mg/5 mL şurup",
   "not": "",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "parasetamol_po_250",
   "ilac_adi": "Parasetamol 250 mg/5 mL",
   "etken_madde": "Parasetamol",
   "markalar": "Calpol 6 Plus",
   "yol": "PO",
   "kategoriler": [
    "Sık kullanılanlar",
    "Şuruplar",
    "Ateş",
    "Ağrı"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 15.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1000.0,
   "gunluk_max_per_kg": 60.0,
   "gunluk_max": 4000.0,
   "tekrar_araligi": "4x1 (dozlar arası en az 4 saat)",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "ölçek",
   "birim_miktar": 250.0,
   "birim_ml": 5.0,
   "form_adi": "250 mg/5 mL şurup",
   "not": "6 yaş ve üstü için.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "ibuprofen_po",
   "ilac_adi": "İbuprofen 100 mg/5 mL",
   "etken_madde": "İbuprofen",
   "markalar": "Brufen; Dorifen",
   "yol": "PO",
   "kategoriler": [
    "Sık kullanılanlar",
    "Şuruplar",
    "Ateş",
    "Ağrı",
    "NSAİİ"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 10.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 400.0,
   "gunluk_max_per_kg": 40.0,
   "gunluk_max": 2400.0,
   "tekrar_araligi": "3-4x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 20.0,
   "birim_adi": "ölçek",
   "birim_miktar": 100.0,
   "birim_ml": 5.0,
   "form_adi": "100 mg/5 mL şurup",
   "not": "6 aydan küçükte kullanılmaz.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "epinefrin_iv_arrest",
   "ilac_adi": "Epinefrin (arrest)",
   "etken_madde": "Epinefrin",
   "markalar": "Adrenalin",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.01,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "3-5 dakikada bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.1,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul (1:1000)",
   "not": "1 mg ampul SF ile 10 mL'ye sulandırılır (0,1 mg/mL = 1:10.000). mL bu sulandırmaya göredir.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "epinefrin_et",
   "ilac_adi": "Epinefrin",
   "etken_madde": "Epinefrin",
   "markalar": "Adrenalin",
   "yol": "ET",
   "kategoriler": [
    "Resüsitasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2.5,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "3-5 dakikada bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul (1:1000)",
   "not": "Sulandırılmadan (1 mg/mL) verilir. IV/IO yol yoksa kullanılır.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "epinefrin_im",
   "ilac_adi": "Epinefrin (anafilaksi)",
   "etken_madde": "Epinefrin",
   "markalar": "Adrenalin",
   "yol": "IM",
   "kategoriler": [
    "Resüsitasyon",
    "Alerji/Anafilaksi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.01,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 0.5,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "5-15 dakikada bir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul (1:1000)",
   "not": "Sulandırılmadan, uyluk dış yanına verilir.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "epinefrin_neb",
   "ilac_adi": "Epinefrin",
   "etken_madde": "Epinefrin",
   "markalar": "Adrenalin",
   "yol": "Nebül",
   "kategoriler": [
    "Resüsitasyon",
    "Solunum",
    "Krup"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 5.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul (1:1000)",
   "not": "Krup: 0,5 mL/kg (max 5 mL), 1 mg/mL koruyucusuz adrenalin. 5-15 dakikada nebülize edilir. Toplam hacim 3 mL'den azsa SF ile 3 mL'ye tamamlanır.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "atropin_iv_bradikardi",
   "ilac_adi": "Atropin (bradikardi)",
   "etken_madde": "Atropin sülfat",
   "markalar": "Atropin",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Aritmi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.02,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": 0.1,
   "tek_doz_max": 0.5,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "1 kez tekrarlanabilir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul",
   "not": "",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "atropin_opp",
   "ilac_adi": "Atropin (OPP)",
   "etken_madde": "Atropin sülfat",
   "markalar": "Atropin",
   "yol": "IV/IM",
   "kategoriler": [
    "Resüsitasyon",
    "Zehirlenme"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.02,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": 0.1,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "5 dakikada bir, doz iki katına çıkarılarak",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul",
   "not": "Organofosfat zehirlenmesi. Atropinizasyon (sekresyonlar kuruyana kadar) sağlanana kadar sürdürülür.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "atropin_et",
   "ilac_adi": "Atropin",
   "etken_madde": "Atropin sülfat",
   "markalar": "Atropin",
   "yol": "ET",
   "kategoriler": [
    "Resüsitasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.04,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL ampul",
   "not": "",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "adenozin_1",
   "ilac_adi": "Adenozin 1. doz",
   "etken_madde": "Adenozin",
   "markalar": "Adenocor",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Aritmi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 6.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 3.0,
   "birim_adi": "ampul",
   "birim_miktar": 6.0,
   "birim_ml": 2.0,
   "form_adi": "6 mg/2 mL ampul",
   "not": "Hızlı IV puşe, hemen ardından 5-10 mL SF ile hızlı yıkama.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "adenozin_2",
   "ilac_adi": "Adenozin 2. doz",
   "etken_madde": "Adenozin",
   "markalar": "Adenocor",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Aritmi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.2,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 12.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 3.0,
   "birim_adi": "ampul",
   "birim_miktar": 6.0,
   "birim_ml": 2.0,
   "form_adi": "6 mg/2 mL ampul",
   "not": "1. doz yanıtsızsa. Hızlı IV puşe, hemen ardından 5-10 mL SF ile hızlı yıkama.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "midazolam_iv",
   "ilac_adi": "Midazolam",
   "etken_madde": "Midazolam",
   "markalar": "Dormicum",
   "yol": "IV",
   "kategoriler": [
    "Resüsitasyon",
    "Nöbet",
    "Entübasyon/Sedasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 5.0,
   "birim_adi": "ampul",
   "birim_miktar": 15.0,
   "birim_ml": 3.0,
   "form_adi": "15 mg/3 mL ampul",
   "not": "5 mg/5 mL (1 mg/mL) ampul kullanılırsa mL farklıdır.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "midazolam_in_im",
   "ilac_adi": "Midazolam",
   "etken_madde": "Midazolam",
   "markalar": "Dormicum",
   "yol": "IN/IM",
   "kategoriler": [
    "Resüsitasyon",
    "Nöbet"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.2,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 10.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 5.0,
   "birim_adi": "ampul",
   "birim_miktar": 15.0,
   "birim_ml": 3.0,
   "form_adi": "15 mg/3 mL ampul",
   "not": "IN: dozu iki burun deliğine bölün.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "morfin_iv_im",
   "ilac_adi": "Morfin",
   "etken_madde": "Morfin sülfat",
   "markalar": "Morfin",
   "yol": "IV/IM",
   "kategoriler": [
    "Resüsitasyon",
    "Ağrı"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2-4 saatte bir",
   "kilo_min_kg": 8.0,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 10.0,
   "birim_adi": "ampul",
   "birim_miktar": 10.0,
   "birim_ml": 1.0,
   "form_adi": "10 mg/1 mL ampul",
   "not": "Broselow tablosunda 8 kg altı için verilmemiş.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "glukagon_im_25alti",
   "ilac_adi": "Glukagon",
   "etken_madde": "Glukagon",
   "markalar": "GlucaGen",
   "yol": "IM",
   "kategoriler": [
    "Resüsitasyon",
    "Hipoglisemi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": null,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": 0.5,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": 25.0,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "flakon",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL kit",
   "not": "25 kg altı sabit doz.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "glukagon_im_25ustu",
   "ilac_adi": "Glukagon",
   "etken_madde": "Glukagon",
   "markalar": "GlucaGen",
   "yol": "IM",
   "kategoriler": [
    "Resüsitasyon",
    "Hipoglisemi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": null,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": 1.0,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": 25.0,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "flakon",
   "birim_miktar": 1.0,
   "birim_ml": 1.0,
   "form_adi": "1 mg/1 mL kit",
   "not": "25 kg ve üstü sabit doz.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "bikarbonat_iv",
   "ilac_adi": "Sodyum bikarbonat %8,4",
   "etken_madde": "Sodyum bikarbonat",
   "markalar": "",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon"
   ],
   "doz_birimi": "mEq",
   "doz_per_kg": 1.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 50.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "ampul",
   "birim_miktar": 10.0,
   "birim_ml": 10.0,
   "form_adi": "10 mEq/10 mL ampul (%8,4)",
   "not": "Yenidoğan ve küçük bebekte 1:1 sulandırılır (%4,2).",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "dekstroz_10",
   "ilac_adi": "Dekstroz %10",
   "etken_madde": "Dekstroz",
   "markalar": "",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Hipoglisemi"
   ],
   "doz_birimi": "g",
   "doz_per_kg": 0.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 25.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.1,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "%10 dekstroz (0,1 g/mL)",
   "not": "0,5 g/kg = 5 mL/kg.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "nalokson",
   "ilac_adi": "Nalokson",
   "etken_madde": "Nalokson",
   "markalar": "Narcan",
   "yol": "IV/IM/IN",
   "kategoriler": [
    "Resüsitasyon",
    "Zehirlenme"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.1,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2-3 dakikada bir, gerekirse",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.4,
   "birim_adi": "ampul",
   "birim_miktar": 0.4,
   "birim_ml": 1.0,
   "form_adi": "0.4 mg/1 mL ampul",
   "not": "",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "sf_bolus",
   "ilac_adi": "SF bolus",
   "etken_madde": "%0,9 NaCl",
   "markalar": "",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Sıvılar"
   ],
   "doz_birimi": "mL",
   "doz_per_kg": 20.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": null,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "%0,9 NaCl",
   "not": "Gerekirse tekrarlanır; her bolustan sonra yeniden değerlendirilir.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "deksametazon_krup",
   "ilac_adi": "Deksametazon (krup)",
   "etken_madde": "Deksametazon",
   "markalar": "Dekort",
   "yol": "PO/IV/IM",
   "kategoriler": [
    "Krup"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.6,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 16.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 4.0,
   "birim_adi": "ampul",
   "birim_miktar": 8.0,
   "birim_ml": 2.0,
   "form_adi": "8 mg/2 mL ampul",
   "not": "En az invaziv yol: ağızdan alabiliyorsa PO, damar yolu varsa IV, ikisi de yoksa IM. PO için ampul ağızdan verilebilir (şurupla karıştırılabilir) veya tablet ezilip püre ile verilir.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "idame_sf",
   "ilac_adi": "SF idame",
   "etken_madde": "%0,9 NaCl",
   "markalar": "",
   "yol": "IV",
   "kategoriler": [
    "Sıvılar"
   ],
   "doz_birimi": "mL/saat",
   "doz_per_kg": null,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 100.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": null,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "%0,9 NaCl",
   "not": "Holliday-Segar (4-2-1): ilk 10 kg için 4 mL/kg/saat, sonraki 10 kg için 2 mL/kg/saat, 20 kg üstü her kg için 1 mL/kg/saat. İzotonik idame güncel önerilen sıvıdır.",
   "hesap_tipi": "holliday_segar",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "idame_yarim_izomiks",
   "ilac_adi": "½ İzomiks idame",
   "etken_madde": "½ İzomiks",
   "markalar": "İzomiks",
   "yol": "IV",
   "kategoriler": [
    "Sıvılar"
   ],
   "doz_birimi": "mL/saat",
   "doz_per_kg": null,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 100.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": null,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "½ İzomiks",
   "not": "Holliday-Segar (4-2-1): ilk 10 kg için 4 mL/kg/saat, sonraki 10 kg için 2 mL/kg/saat, 20 kg üstü her kg için 1 mL/kg/saat. Hipotonik sıvı: hiponatremi riskine dikkat.",
   "hesap_tipi": "holliday_segar",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "amoks_klav_bid",
   "ilac_adi": "Amoksisilin-klavulanat 400/57",
   "etken_madde": "Amoksisilin-klavulanat",
   "markalar": "Augmentin BID; Klamoks BID; Amoklavin BID; Aklav BID; Klavunat BID",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 22.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 875.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 80.0,
   "birim_adi": "ölçek",
   "birim_miktar": 400.0,
   "birim_ml": 5.0,
   "form_adi": "400/57 mg / 5 mL süspansiyon",
   "not": "Doz amoksisiline göredir. Standart doz: 45 mg/kg/gün, 2'ye bölünmüş.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "amoks_klav_es",
   "ilac_adi": "Amoksisilin-klavulanat 600/42,9 (ES)",
   "etken_madde": "Amoksisilin-klavulanat",
   "markalar": "Augmentin ES-600; Klamoks ES; Klavon ES; Klavunat ES; Moksivesta ES",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 45.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 120.0,
   "birim_adi": "ölçek",
   "birim_miktar": 600.0,
   "birim_ml": 5.0,
   "form_adi": "600/42,9 mg / 5 mL süspansiyon",
   "not": "Doz amoksisiline göredir. Yüksek doz: 90 mg/kg/gün, 2'ye bölünmüş. OM, sinüzit, pnömoni.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "amoksisilin_po",
   "ilac_adi": "Amoksisilin 250 mg/5 mL",
   "etken_madde": "Amoksisilin",
   "markalar": "Largopen; Alfoxil Forte",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 45.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": 4000.0,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "ölçek",
   "birim_miktar": 250.0,
   "birim_ml": 5.0,
   "form_adi": "250 mg/5 mL süspansiyon",
   "not": "Yüksek doz: 90 mg/kg/gün, 2'ye bölünmüş. OM, pnömoni.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "sefuroksim_125",
   "ilac_adi": "Sefuroksim 125 mg/5 mL",
   "etken_madde": "Sefuroksim aksetil",
   "markalar": "Zinnat; Cefaks; Sefuroks",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 15.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 500.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 25.0,
   "birim_adi": "ölçek",
   "birim_miktar": 125.0,
   "birim_ml": 5.0,
   "form_adi": "125 mg/5 mL süspansiyon",
   "not": "30 mg/kg/gün, 2'ye bölünmüş.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "sefuroksim_250",
   "ilac_adi": "Sefuroksim 250 mg/5 mL",
   "etken_madde": "Sefuroksim aksetil",
   "markalar": "Zinnat; Cefaks",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 15.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 500.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "ölçek",
   "birim_miktar": 250.0,
   "birim_ml": 5.0,
   "form_adi": "250 mg/5 mL süspansiyon",
   "not": "30 mg/kg/gün, 2'ye bölünmüş.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "sefiksim_po",
   "ilac_adi": "Sefiksim 100 mg/5 mL",
   "etken_madde": "Sefiksim",
   "markalar": "Suprax; Zimaks; Molcef; Fixef",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 8.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 400.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "1x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 20.0,
   "birim_adi": "ölçek",
   "birim_miktar": 100.0,
   "birim_ml": 5.0,
   "form_adi": "100 mg/5 mL süspansiyon",
   "not": "8 mg/kg/gün, günde tek doz.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "sefdinir_125",
   "ilac_adi": "Sefdinir 125 mg/5 mL",
   "etken_madde": "Sefdinir",
   "markalar": "Encef; Menacef; Seforin; Ceforist; Ceftinex; Klasef",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 14.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 600.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "1x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 25.0,
   "birim_adi": "ölçek",
   "birim_miktar": 125.0,
   "birim_ml": 5.0,
   "form_adi": "125 mg/5 mL süspansiyon",
   "not": "14 mg/kg/gün, günde tek doz.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "sefdinir_250",
   "ilac_adi": "Sefdinir 250 mg/5 mL",
   "etken_madde": "Sefdinir",
   "markalar": "Encef; Menacef; Seforin; Rodinir; Tricef; Tamcef",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 14.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 600.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "1x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "ölçek",
   "birim_miktar": 250.0,
   "birim_ml": 5.0,
   "form_adi": "250 mg/5 mL süspansiyon",
   "not": "14 mg/kg/gün, günde tek doz.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "klaritromisin_125",
   "ilac_adi": "Klaritromisin 125 mg/5 mL",
   "etken_madde": "Klaritromisin",
   "markalar": "Klacid; Klamaxin; Klaromin; Maxiclar; Laricid; Klarolid; Klamer",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 7.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 500.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 25.0,
   "birim_adi": "ölçek",
   "birim_miktar": 125.0,
   "birim_ml": 5.0,
   "form_adi": "125 mg/5 mL süspansiyon",
   "not": "15 mg/kg/gün, 2'ye bölünmüş.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "klaritromisin_250",
   "ilac_adi": "Klaritromisin 250 mg/5 mL",
   "etken_madde": "Klaritromisin",
   "markalar": "Klacid; Klamaxin; Klaromin; Maxiclar; Laricid; Klarolid; Klamer",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 7.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 500.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "ölçek",
   "birim_miktar": 250.0,
   "birim_ml": 5.0,
   "form_adi": "250 mg/5 mL süspansiyon",
   "not": "15 mg/kg/gün, 2'ye bölünmüş.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "azitromisin_po",
   "ilac_adi": "Azitromisin 200 mg/5 mL",
   "etken_madde": "Azitromisin",
   "markalar": "Azro; Zitromax",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 10.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 500.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "1x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 40.0,
   "birim_adi": "ölçek",
   "birim_miktar": 200.0,
   "birim_ml": 5.0,
   "form_adi": "200 mg/5 mL süspansiyon",
   "not": "5 günlük tedavi, günde tek doz: 1. gün 10 mg/kg (max 500 mg), 2–5. gün 5 mg/kg (max 250 mg).",
   "hesap_tipi": "",
   "doz_etiket": "1. gün",
   "ikinci_doz_per_kg": 5.0,
   "ikinci_doz_max": 250.0,
   "ikinci_doz_etiket": "2–5. gün"
  },
  {
   "id": "tmp_smx_po",
   "ilac_adi": "TMP-SMX 40/200 mg/5 mL",
   "etken_madde": "Trimetoprim-sulfametoksazol",
   "markalar": "Bactrim; Kemoprim; Trimoks",
   "yol": "PO",
   "kategoriler": [
    "Antibiyotikler",
    "Şuruplar"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 4.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 160.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 8.0,
   "birim_adi": "ölçek",
   "birim_miktar": 40.0,
   "birim_ml": 5.0,
   "form_adi": "40/200 mg / 5 mL süspansiyon",
   "not": "Doz trimetoprime göredir. 8 mg/kg/gün, 2'ye bölünmüş. 2 aydan küçükte kullanılmaz.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "salbutamol_neb",
   "ilac_adi": "Salbutamol",
   "etken_madde": "Salbutamol",
   "markalar": "Ventolin",
   "yol": "Nebül",
   "kategoriler": [
    "Astım"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.15,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": 2.5,
   "tek_doz_max": 5.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "20 dakikada bir, 3 kez",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 1.0,
   "birim_adi": "nebül",
   "birim_miktar": 2.5,
   "birim_ml": 2.5,
   "form_adi": "2,5 mg/2,5 mL nebül",
   "not": "Toplam hacim 3 mL'den azsa SF ile 3 mL'ye tamamlanır.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "ipratropium_20alti",
   "ilac_adi": "İpratropium",
   "etken_madde": "İpratropium bromür",
   "markalar": "İpratom; Atrovent",
   "yol": "Nebül",
   "kategoriler": [
    "Astım"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": null,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": 0.25,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "20 dakikada bir, 3 kez (salbutamol ile)",
   "kilo_min_kg": null,
   "kilo_max_kg": 20.0,
   "konsantrasyon_per_ml": 0.25,
   "birim_adi": "nebül",
   "birim_miktar": 0.5,
   "birim_ml": 2.0,
   "form_adi": "500 mcg/2 mL nebül",
   "not": "20 kg altı sabit doz: 250 mcg. Orta-ağır astım atağında salbutamol ile birlikte.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "ipratropium_20ustu",
   "ilac_adi": "İpratropium",
   "etken_madde": "İpratropium bromür",
   "markalar": "İpratom; Atrovent",
   "yol": "Nebül",
   "kategoriler": [
    "Astım"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": null,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": 0.5,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "20 dakikada bir, 3 kez (salbutamol ile)",
   "kilo_min_kg": 20.0,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.25,
   "birim_adi": "nebül",
   "birim_miktar": 0.5,
   "birim_ml": 2.0,
   "form_adi": "500 mcg/2 mL nebül",
   "not": "20 kg ve üstü sabit doz: 500 mcg. Orta-ağır astım atağında salbutamol ile birlikte.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "budesonid_neb",
   "ilac_adi": "Budesonid",
   "etken_madde": "Budesonid",
   "markalar": "Pulmicort",
   "yol": "Nebül",
   "kategoriler": [
    "Krup"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": null,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": 2.0,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.5,
   "birim_adi": "nebül",
   "birim_miktar": 1.0,
   "birim_ml": 2.0,
   "form_adi": "1 mg/2 mL nebül",
   "not": "Krup: tek doz 2 mg. Deksametazon verilemiyorsa veya ek olarak.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "metilprednizolon_iv",
   "ilac_adi": "Metilprednizolon",
   "etken_madde": "Metilprednizolon",
   "markalar": "Prednol-L",
   "yol": "IV/IM",
   "kategoriler": [
    "Astım",
    "Alerji/Anafilaksi"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 1.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 60.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "4x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 20.0,
   "birim_adi": "flakon",
   "birim_miktar": 40.0,
   "birim_ml": 2.0,
   "form_adi": "40 mg flakon + 2 mL çözücü (20 mg/mL)",
   "not": "Ağır astım: ilk doz 1–2 mg/kg (max 60 mg), sonra 1 mg/kg 6 saatte bir.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "prednizolon_po",
   "ilac_adi": "Prednizolon",
   "etken_madde": "Prednizolon",
   "markalar": "Deltacortril",
   "yol": "PO",
   "kategoriler": [
    "Astım"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 1.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 40.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "1x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": null,
   "birim_adi": "tablet",
   "birim_miktar": 5.0,
   "birim_ml": null,
   "form_adi": "5 mg tablet",
   "not": "1–2 mg/kg/gün, günde tek doz, 3–5 gün. 2 yaş altı max 20 mg, 2–5 yaş max 30 mg.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "magnezyum_iv",
   "ilac_adi": "Magnezyum sülfat",
   "etken_madde": "Magnezyum sülfat",
   "markalar": "",
   "yol": "IV",
   "kategoriler": [
    "Astım"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 40.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 150.0,
   "birim_adi": "ampul",
   "birim_miktar": 1500.0,
   "birim_ml": 10.0,
   "form_adi": "%15, 1,5 g/10 mL ampul",
   "not": "Ağır astım. 20 dakikada infüzyon. Hipotansiyon ve bradikardi için izleyin.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "diazepam_rektal",
   "ilac_adi": "Diazepam rektal",
   "etken_madde": "Diazepam",
   "markalar": "Diaksi; Diazepam Desitin",
   "yol": "Rektal",
   "kategoriler": [
    "Nöbet"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 10.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "10 dakika sonra 1 kez tekrarlanabilir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": null,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "5 mg/2,5 mL ve 10 mg/2,5 mL rektal tüp",
   "not": "Hesaplanan doza en yakın tüpü seçin: 5 mg veya 10 mg.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "diazepam_iv",
   "ilac_adi": "Diazepam",
   "etken_madde": "Diazepam",
   "markalar": "Diazem",
   "yol": "IV",
   "kategoriler": [
    "Nöbet"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.2,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 10.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "5–10 dakika sonra 1 kez tekrarlanabilir",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 5.0,
   "birim_adi": "ampul",
   "birim_miktar": 10.0,
   "birim_ml": 2.0,
   "form_adi": "10 mg/2 mL ampul",
   "not": "Yavaş IV (2–5 dakikada). Solunum depresyonu için izleyin.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "levetirasetam_iv",
   "ilac_adi": "Levetirasetam",
   "etken_madde": "Levetirasetam",
   "markalar": "Keppra",
   "yol": "IV",
   "kategoriler": [
    "Nöbet"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 60.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 4500.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 100.0,
   "birim_adi": "flakon",
   "birim_miktar": 500.0,
   "birim_ml": 5.0,
   "form_adi": "500 mg/5 mL flakon",
   "not": "AES kılavuzu ve ESETT: 60 mg/kg (max 4,5 g), 10 dakikada. Status epileptikus ikinci basamak. SF ile sulandırılır. İngiltere APLS: 40 mg/kg (max 3 g).",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "fenitoin_iv",
   "ilac_adi": "Fenitoin",
   "etken_madde": "Fenitoin sodyum",
   "markalar": "Epitoin; Toinex; Fenitosel",
   "yol": "IV",
   "kategoriler": [
    "Nöbet"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 20.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 1500.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "ampul",
   "birim_miktar": 250.0,
   "birim_ml": 5.0,
   "form_adi": "250 mg/5 mL ampul",
   "not": "Sadece SF ile sulandırılır (dekstrozla çöker). Hız en fazla 1 mg/kg/dakika (max 50 mg/dakika). Kardiyak monitör.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "ketamin_iv",
   "ilac_adi": "Ketamin",
   "etken_madde": "Ketamin",
   "markalar": "Ketalar",
   "yol": "IV",
   "kategoriler": [
    "Entübasyon/Sedasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 2.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "flakon",
   "birim_miktar": 500.0,
   "birim_ml": 10.0,
   "form_adi": "500 mg/10 mL flakon",
   "not": "Entübasyon: 1–2 mg/kg. Prosedürel sedasyon: 1–1,5 mg/kg IV veya 4 mg/kg IM.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "propofol_iv",
   "ilac_adi": "Propofol",
   "etken_madde": "Propofol",
   "markalar": "Propofol-PF; Propofol-Haver",
   "yol": "IV",
   "kategoriler": [
    "Entübasyon/Sedasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 2.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 10.0,
   "birim_adi": "ampul",
   "birim_miktar": 200.0,
   "birim_ml": 20.0,
   "form_adi": "%1, 200 mg/20 mL ampul",
   "not": "İndüksiyon: 1–2,5 mg/kg. Sedasyon: 1 mg/kg. Hipotansiyon yapar; şokta dikkat.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "rokuronyum_iv",
   "ilac_adi": "Roküronyum",
   "etken_madde": "Roküronyum bromür",
   "markalar": "Esmeron",
   "yol": "IV",
   "kategoriler": [
    "Entübasyon/Sedasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 1.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 10.0,
   "birim_adi": "flakon",
   "birim_miktar": 50.0,
   "birim_ml": 5.0,
   "form_adi": "50 mg/5 mL flakon",
   "not": "Hızlı ardışık entübasyon: 1–1,2 mg/kg.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "suksinilkolin_iv",
   "ilac_adi": "Süksinilkolin",
   "etken_madde": "Süksinilkolin",
   "markalar": "Lysthenon Forte",
   "yol": "IV",
   "kategoriler": [
    "Entübasyon/Sedasyon"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 1.5,
   "doz_10kg_alti_per_kg": 2.0,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 150.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 20.0,
   "birim_adi": "ampul",
   "birim_miktar": 100.0,
   "birim_ml": 5.0,
   "form_adi": "%2, 100 mg/5 mL ampul",
   "not": "Bradikardi yapabilir; küçük çocukta atropin hazır olsun. Hiperkalemi, nöromüsküler hastalık ve 48 saatten eski yanık/ezilmede kontrendike. Buzdolabında saklanır.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "fentanil_iv",
   "ilac_adi": "Fentanil",
   "etken_madde": "Fentanil",
   "markalar": "Talinat; Fentaver",
   "yol": "IV",
   "kategoriler": [
    "Entübasyon/Sedasyon",
    "Ağrı"
   ],
   "doz_birimi": "mcg",
   "doz_per_kg": 1.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 100.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "ampul",
   "birim_miktar": 100.0,
   "birim_ml": 2.0,
   "form_adi": "0,1 mg/2 mL ampul (50 mcg/mL)",
   "not": "1–2 mcg/kg, yavaş IV. Hızlı verilirse göğüs duvarı rijiditesi yapabilir.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "fentanil_in",
   "ilac_adi": "Fentanil",
   "etken_madde": "Fentanil",
   "markalar": "Talinat; Fentaver",
   "yol": "IN",
   "kategoriler": [
    "Ağrı"
   ],
   "doz_birimi": "mcg",
   "doz_per_kg": 1.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 100.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "ampul",
   "birim_miktar": 100.0,
   "birim_ml": 2.0,
   "form_adi": "0,1 mg/2 mL ampul (50 mcg/mL)",
   "not": "Sulandırılmadan, atomizörle (MAD) iki burun deliğine bölünerek verilir.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "seftriakson_iv",
   "ilac_adi": "Seftriakson",
   "etken_madde": "Seftriakson",
   "markalar": "Rocephin; Novosef",
   "yol": "IV",
   "kategoriler": [
    "Antibiyotikler"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 50.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "1x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 100.0,
   "birim_adi": "flakon",
   "birim_miktar": 1000.0,
   "birim_ml": 10.0,
   "form_adi": "1 g flakon (10 mL ile 100 mg/mL)",
   "not": "Kalsiyumlu sıvılarla aynı hattan verilmez.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "seftriakson_menenjit",
   "ilac_adi": "Seftriakson (menenjit)",
   "etken_madde": "Seftriakson",
   "markalar": "Rocephin; Novosef",
   "yol": "IV",
   "kategoriler": [
    "Antibiyotikler"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 50.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "2x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 100.0,
   "birim_adi": "flakon",
   "birim_miktar": 1000.0,
   "birim_ml": 10.0,
   "form_adi": "1 g flakon (10 mL ile 100 mg/mL)",
   "not": "Menenjit: 100 mg/kg/gün, 2'ye bölünmüş (max 4 g/gün). Kalsiyumlu sıvılarla aynı hattan verilmez.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "ampisilin_iv",
   "ilac_adi": "Ampisilin",
   "etken_madde": "Ampisilin",
   "markalar": "Ampisina; Alfasilin",
   "yol": "IV",
   "kategoriler": [
    "Antibiyotikler"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 50.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "4x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 100.0,
   "birim_adi": "flakon",
   "birim_miktar": 1000.0,
   "birim_ml": 10.0,
   "form_adi": "1 g flakon (10 mL ile 100 mg/mL)",
   "not": "200 mg/kg/gün, 4'e bölünmüş.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "ampisilin_menenjit",
   "ilac_adi": "Ampisilin (menenjit)",
   "etken_madde": "Ampisilin",
   "markalar": "Ampisina; Alfasilin",
   "yol": "IV",
   "kategoriler": [
    "Antibiyotikler"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 75.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 2000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "4x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 100.0,
   "birim_adi": "flakon",
   "birim_miktar": 1000.0,
   "birim_ml": 10.0,
   "form_adi": "1 g flakon (10 mL ile 100 mg/mL)",
   "not": "Menenjit: 300 mg/kg/gün, 4'e bölünmüş.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "vankomisin_iv",
   "ilac_adi": "Vankomisin",
   "etken_madde": "Vankomisin",
   "markalar": "Vancotek; Edicin; Vamycin; Vankomyl; Vankopol",
   "yol": "IV",
   "kategoriler": [
    "Antibiyotikler"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 15.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "4x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 50.0,
   "birim_adi": "flakon",
   "birim_miktar": 500.0,
   "birim_ml": 10.0,
   "form_adi": "500 mg flakon (10 mL ile 50 mg/mL)",
   "not": "En fazla 5 mg/mL olacak şekilde seyreltilip en az 60 dakikada verilir (kırmızı adam sendromu). mL değeri 50 mg/mL sulandırmaya göredir.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "asiklovir_iv",
   "ilac_adi": "Asiklovir",
   "etken_madde": "Asiklovir",
   "markalar": "Klovireks-L; Asirax",
   "yol": "IV",
   "kategoriler": [
    "Antibiyotikler"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 20.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": null,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "3x1",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 25.0,
   "birim_adi": "flakon",
   "birim_miktar": 250.0,
   "birim_ml": 10.0,
   "form_adi": "250 mg flakon (10 mL ile 25 mg/mL)",
   "not": "HSV ensefaliti (12 yaş altı). 12 yaş ve üstü: 10 mg/kg 3x1. En az 1 saatte infüzyon; iyi hidrasyon.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "kalsiyum_glukonat",
   "ilac_adi": "Kalsiyum (Calciles)",
   "etken_madde": "Kalsiyum glukonat + kalsiyum levulinat",
   "markalar": "Calciles; Calciosel",
   "yol": "IV/IO",
   "kategoriler": [
    "Resüsitasyon",
    "Elektrolit/KİBAS"
   ],
   "doz_birimi": "mL",
   "doz_per_kg": 0.6,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 30.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": null,
   "birim_adi": "ampul",
   "birim_miktar": 10.0,
   "birim_ml": 10.0,
   "form_adi": "10 mL ampul (225 mg kalsiyum glukonat + 572 mg kalsiyum levulinat)",
   "not": "%10 kalsiyum glukonat karşılığı olarak kullanılır: 0,5–0,6 mL/kg (max 30 mL). 5–10 dakikada yavaş IV, tercihen büyük ven. Hiperkalemi, hipokalsemi, kalsiyum kanal blokeri zehirlenmesi.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "nacl_3",
   "ilac_adi": "%3 NaCl",
   "etken_madde": "%3 NaCl",
   "markalar": "",
   "yol": "IV",
   "kategoriler": [
    "Elektrolit/KİBAS"
   ],
   "doz_birimi": "mL",
   "doz_per_kg": 5.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 250.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": null,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "%3 NaCl",
   "not": "KİBAS: 3–5 mL/kg, 10–20 dakikada. Semptomatik hiponatremi: 2 mL/kg (max 100 mL), gerekirse tekrar.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "mannitol",
   "ilac_adi": "Mannitol %20",
   "etken_madde": "Mannitol",
   "markalar": "",
   "yol": "IV",
   "kategoriler": [
    "Elektrolit/KİBAS"
   ],
   "doz_birimi": "g",
   "doz_per_kg": 0.5,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 50.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.2,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "%20 mannitol (0,2 g/mL)",
   "not": "KİBAS: 0,5–1 g/kg, 20 dakikada. İdrar sondası takın; hipovolemiden kaçının.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "aktif_komur",
   "ilac_adi": "Aktif kömür",
   "etken_madde": "Aktif kömür",
   "markalar": "Toxicarb; Optimaven; Carbomix",
   "yol": "PO/NG",
   "kategoriler": [
    "Zehirlenme"
   ],
   "doz_birimi": "g",
   "doz_per_kg": 1.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 50.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.2,
   "birim_adi": "",
   "birim_miktar": null,
   "birim_ml": null,
   "form_adi": "Süspansiyon (Toxicarb 12 g/60 mL = 0,2 g/mL)",
   "not": "En etkili ilk 1 saatte. Hava yolu korunmuyorsa verilmez. Demir, lityum, alkol ve korozivlerde etkisiz.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  },
  {
   "id": "nac_iv_20alti",
   "ilac_adi": "N-asetilsistein (2 torba)",
   "etken_madde": "Asetilsistein",
   "markalar": "Asist",
   "yol": "IV",
   "kategoriler": [
    "Zehirlenme"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 200.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 22000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": null,
   "kilo_max_kg": 20.0,
   "konsantrasyon_per_ml": 100.0,
   "birim_adi": "ampul",
   "birim_miktar": 300.0,
   "birim_ml": 3.0,
   "form_adi": "300 mg/3 mL ampul",
   "not": "20 kg altı. Hazır %5 dekstroz veya SF torbası kullanın: önce torbadan NAC hacmi kadar sıvı çekin, sonra NAC'ı ekleyin.",
   "hesap_tipi": "",
   "doz_etiket": "1. torba: toplam 100 mL, 4 saatte (25 mL/saat)",
   "ikinci_doz_per_kg": 100.0,
   "ikinci_doz_max": 11000.0,
   "ikinci_doz_etiket": "2. torba: toplam 250 mL, 16 saatte (15,6 mL/saat)"
  },
  {
   "id": "nac_iv_20_50",
   "ilac_adi": "N-asetilsistein (2 torba)",
   "etken_madde": "Asetilsistein",
   "markalar": "Asist",
   "yol": "IV",
   "kategoriler": [
    "Zehirlenme"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 200.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 22000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": 20.0,
   "kilo_max_kg": 50.0,
   "konsantrasyon_per_ml": 100.0,
   "birim_adi": "ampul",
   "birim_miktar": 300.0,
   "birim_ml": 3.0,
   "form_adi": "300 mg/3 mL ampul",
   "not": "20–50 kg. Hazır %5 dekstroz veya SF torbası kullanın: önce torbadan NAC hacmi kadar sıvı çekin, sonra NAC'ı ekleyin.",
   "hesap_tipi": "",
   "doz_etiket": "1. torba: toplam 250 mL, 4 saatte (62,5 mL/saat)",
   "ikinci_doz_per_kg": 100.0,
   "ikinci_doz_max": 11000.0,
   "ikinci_doz_etiket": "2. torba: toplam 500 mL, 16 saatte (31,3 mL/saat)"
  },
  {
   "id": "nac_iv_50ustu",
   "ilac_adi": "N-asetilsistein (2 torba)",
   "etken_madde": "Asetilsistein",
   "markalar": "Asist",
   "yol": "IV",
   "kategoriler": [
    "Zehirlenme"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 200.0,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 22000.0,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "",
   "kilo_min_kg": 50.0,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 100.0,
   "birim_adi": "ampul",
   "birim_miktar": 300.0,
   "birim_ml": 3.0,
   "form_adi": "300 mg/3 mL ampul",
   "not": "50 kg ve üstü. Hazır %5 dekstroz veya SF torbası kullanın: önce torbadan NAC hacmi kadar sıvı çekin, sonra NAC'ı ekleyin. Hesapta en fazla 110 kg kullanılır.",
   "hesap_tipi": "",
   "doz_etiket": "1. torba: toplam 500 mL, 4 saatte (125 mL/saat)",
   "ikinci_doz_per_kg": 100.0,
   "ikinci_doz_max": 11000.0,
   "ikinci_doz_etiket": "2. torba: toplam 1000 mL, 16 saatte (62,5 mL/saat)"
  },
  {
   "id": "flumazenil_iv",
   "ilac_adi": "Flumazenil",
   "etken_madde": "Flumazenil",
   "markalar": "Anesed-R; Lauzenil; Mazenil; Fluxate",
   "yol": "IV",
   "kategoriler": [
    "Zehirlenme"
   ],
   "doz_birimi": "mg",
   "doz_per_kg": 0.01,
   "doz_10kg_alti_per_kg": null,
   "sabit_doz": null,
   "tek_doz_min": null,
   "tek_doz_max": 0.2,
   "gunluk_max_per_kg": null,
   "gunluk_max": null,
   "tekrar_araligi": "1 dakikada bir, toplam max 1 mg (0,05 mg/kg)",
   "kilo_min_kg": null,
   "kilo_max_kg": null,
   "konsantrasyon_per_ml": 0.1,
   "birim_adi": "ampul",
   "birim_miktar": 0.5,
   "birim_ml": 5.0,
   "form_adi": "0,5 mg/5 mL ampul",
   "not": "Kronik benzodiazepin kullanımı, nöbet öyküsü ve trisiklik zehirlenmesinde nöbet riski; bu durumlarda verilmez.",
   "hesap_tipi": "",
   "doz_etiket": "",
   "ikinci_doz_per_kg": null,
   "ikinci_doz_max": null,
   "ikinci_doz_etiket": ""
  }
 ],
 "broselow": [
  {
   "renk": "Gri / Pembe",
   "kilo_min_kg": 0.0,
   "kilo_max_kg": 8.0,
   "kilo_araligi": "<8 kg",
   "ornek_kilo": "~5 kg",
   "boy_cm": "46–59",
   "et_tup_kafsiz_mm": "3.5",
   "et_tup_kafli_mm": "3.0",
   "ng_tup": "5 Fr",
   "defib_1_sok": "10 J",
   "defib_2_3_sok": "20 J",
   "kardiyoversiyon_1_sok": "5 J",
   "kardiyoversiyon_2_3_sok": "10 J"
  },
  {
   "renk": "Kırmızı / Mor / Sarı",
   "kilo_min_kg": 8.0,
   "kilo_max_kg": 15.0,
   "kilo_araligi": "8–14 kg",
   "ornek_kilo": "~10 kg",
   "boy_cm": "67–95",
   "et_tup_kafsiz_mm": "3.5 (K) / 4.0 (M) / 4.5 (S)",
   "et_tup_kafli_mm": "3.0 (K) / 3.5 (M) / 4.0 (S)",
   "ng_tup": "5–8 (K) / 8–10 (M) / 10 (S) Fr",
   "defib_1_sok": "20 J",
   "defib_2_3_sok": "40 J",
   "kardiyoversiyon_1_sok": "10 J",
   "kardiyoversiyon_2_3_sok": "20 J"
  },
  {
   "renk": "Beyaz",
   "kilo_min_kg": 15.0,
   "kilo_max_kg": 19.0,
   "kilo_araligi": "15–18 kg",
   "ornek_kilo": "~15 kg",
   "boy_cm": "96–107",
   "et_tup_kafsiz_mm": "5",
   "et_tup_kafli_mm": "4.5",
   "ng_tup": "10 Fr",
   "defib_1_sok": "30 J",
   "defib_2_3_sok": "60 J",
   "kardiyoversiyon_1_sok": "15 J",
   "kardiyoversiyon_2_3_sok": "30 J"
  },
  {
   "renk": "Mavi",
   "kilo_min_kg": 19.0,
   "kilo_max_kg": 24.0,
   "kilo_araligi": "19–23 kg",
   "ornek_kilo": "~20 kg",
   "boy_cm": "108–117",
   "et_tup_kafsiz_mm": "5.5",
   "et_tup_kafli_mm": "5.0",
   "ng_tup": "12–14 Fr",
   "defib_1_sok": "40 J",
   "defib_2_3_sok": "80 J",
   "kardiyoversiyon_1_sok": "20 J",
   "kardiyoversiyon_2_3_sok": "40 J"
  },
  {
   "renk": "Turuncu",
   "kilo_min_kg": 24.0,
   "kilo_max_kg": 30.0,
   "kilo_araligi": "24–29 kg",
   "ornek_kilo": "~25 kg",
   "boy_cm": "118–127",
   "et_tup_kafsiz_mm": "6",
   "et_tup_kafli_mm": "5.5",
   "ng_tup": "14–18 Fr",
   "defib_1_sok": "50 J",
   "defib_2_3_sok": "100 J",
   "kardiyoversiyon_1_sok": "25 J",
   "kardiyoversiyon_2_3_sok": "50 J"
  },
  {
   "renk": "Yeşil",
   "kilo_min_kg": 30.0,
   "kilo_max_kg": 37.0,
   "kilo_araligi": "30–36 kg",
   "ornek_kilo": "~35 kg",
   "boy_cm": "128–143",
   "et_tup_kafsiz_mm": "6.5",
   "et_tup_kafli_mm": "6.0",
   "ng_tup": "18 Fr",
   "defib_1_sok": "70 J",
   "defib_2_3_sok": "140 J",
   "kardiyoversiyon_1_sok": "35 J",
   "kardiyoversiyon_2_3_sok": "70 J"
  }
 ]
};
